version: "3.8"

services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: fastify.Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/backend
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: postgres:latest
    container_name: ownapi-postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:
