version: "3.8"

services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: fastify.Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/backend
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    container_name: postgres
    hostname: postgres
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
