version: "3.8"

services:
  # backend:
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: fastify.Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/backend
  #   ports:
  #     - 8080:8080
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
