version: "3.8"

services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: fastify.Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/backend
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    container_name: postgres
    hostname: postgres
    user: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ownapidb
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
